/*
 * generated by Xtext 2.30.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.ui.tests;

import com.epistimis.face.ui.internal.FaceActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FaceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FaceActivator.getInstance().getInjector("com.epistimis.face.Face");
	}

}
