/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import com.epistimis.uddl.uddl.DataModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Architecture Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.ArchitectureModel#getDm <em>Dm</em>}</li>
 *   <li>{@link com.epistimis.face.face.ArchitectureModel#getUm <em>Um</em>}</li>
 *   <li>{@link com.epistimis.face.face.ArchitectureModel#getIm <em>Im</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getArchitectureModel()
 * @model
 * @generated
 */
public interface ArchitectureModel extends FaceElement
{
  /**
   * Returns the value of the '<em><b>Dm</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.uddl.uddl.DataModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dm</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getArchitectureModel_Dm()
   * @model containment="true"
   * @generated
   */
  EList<DataModel> getDm();

  /**
   * Returns the value of the '<em><b>Um</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.face.face.UopUoPModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Um</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getArchitectureModel_Um()
   * @model containment="true"
   * @generated
   */
  EList<UopUoPModel> getUm();

  /**
   * Returns the value of the '<em><b>Im</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.face.face.IntegrationIntegrationModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Im</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getArchitectureModel_Im()
   * @model containment="true"
   * @generated
   */
  EList<IntegrationIntegrationModel> getIm();

} // ArchitectureModel
