/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see com.epistimis.face.face.FacePackage
 * @generated
 */
public interface FaceFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FaceFactory eINSTANCE = com.epistimis.face.face.impl.FaceFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Architecture Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Architecture Model</em>'.
   * @generated
   */
  ArchitectureModel createArchitectureModel();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  FaceElement createFaceElement();

  /**
   * Returns a new object of class '<em>Uop Uo PModel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Uo PModel</em>'.
   * @generated
   */
  UopUoPModel createUopUoPModel();

  /**
   * Returns a new object of class '<em>Uop Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Element</em>'.
   * @generated
   */
  UopElement createUopElement();

  /**
   * Returns a new object of class '<em>Uop Supporting Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Supporting Component</em>'.
   * @generated
   */
  UopSupportingComponent createUopSupportingComponent();

  /**
   * Returns a new object of class '<em>Uop Language Runtime</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Language Runtime</em>'.
   * @generated
   */
  UopLanguageRuntime createUopLanguageRuntime();

  /**
   * Returns a new object of class '<em>Uop Component Framework</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Component Framework</em>'.
   * @generated
   */
  UopComponentFramework createUopComponentFramework();

  /**
   * Returns a new object of class '<em>Uop Abstract Uo P</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Abstract Uo P</em>'.
   * @generated
   */
  UopAbstractUoP createUopAbstractUoP();

  /**
   * Returns a new object of class '<em>Uop Abstract Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Abstract Connection</em>'.
   * @generated
   */
  UopAbstractConnection createUopAbstractConnection();

  /**
   * Returns a new object of class '<em>Uop Unit Of Portability</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Unit Of Portability</em>'.
   * @generated
   */
  UopUnitOfPortability createUopUnitOfPortability();

  /**
   * Returns a new object of class '<em>Uop Portable Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Portable Component</em>'.
   * @generated
   */
  UopPortableComponent createUopPortableComponent();

  /**
   * Returns a new object of class '<em>Uop Platform Specific Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Platform Specific Component</em>'.
   * @generated
   */
  UopPlatformSpecificComponent createUopPlatformSpecificComponent();

  /**
   * Returns a new object of class '<em>Uop Thread</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Thread</em>'.
   * @generated
   */
  UopThread createUopThread();

  /**
   * Returns a new object of class '<em>Uop RAM Memory Requirements</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop RAM Memory Requirements</em>'.
   * @generated
   */
  UopRAMMemoryRequirements createUopRAMMemoryRequirements();

  /**
   * Returns a new object of class '<em>Uop Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Connection</em>'.
   * @generated
   */
  UopConnection createUopConnection();

  /**
   * Returns a new object of class '<em>Uop Client Server Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Client Server Connection</em>'.
   * @generated
   */
  UopClientServerConnection createUopClientServerConnection();

  /**
   * Returns a new object of class '<em>Uop Pub Sub Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Pub Sub Connection</em>'.
   * @generated
   */
  UopPubSubConnection createUopPubSubConnection();

  /**
   * Returns a new object of class '<em>Uop Queuing Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Queuing Connection</em>'.
   * @generated
   */
  UopQueuingConnection createUopQueuingConnection();

  /**
   * Returns a new object of class '<em>Uop Single Instance Message Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Single Instance Message Connection</em>'.
   * @generated
   */
  UopSingleInstanceMessageConnection createUopSingleInstanceMessageConnection();

  /**
   * Returns a new object of class '<em>Uop Life Cycle Management Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Life Cycle Management Port</em>'.
   * @generated
   */
  UopLifeCycleManagementPort createUopLifeCycleManagementPort();

  /**
   * Returns a new object of class '<em>Uop Message Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Message Type</em>'.
   * @generated
   */
  UopMessageType createUopMessageType();

  /**
   * Returns a new object of class '<em>Uop Composite Template</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Composite Template</em>'.
   * @generated
   */
  UopCompositeTemplate createUopCompositeTemplate();

  /**
   * Returns a new object of class '<em>Uop Template Composition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Template Composition</em>'.
   * @generated
   */
  UopTemplateComposition createUopTemplateComposition();

  /**
   * Returns a new object of class '<em>Uop Template</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Uop Template</em>'.
   * @generated
   */
  UopTemplate createUopTemplate();

  /**
   * Returns a new object of class '<em>Integration Integration Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Integration Model</em>'.
   * @generated
   */
  IntegrationIntegrationModel createIntegrationIntegrationModel();

  /**
   * Returns a new object of class '<em>Integration Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Element</em>'.
   * @generated
   */
  IntegrationElement createIntegrationElement();

  /**
   * Returns a new object of class '<em>Integration Integration Context</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Integration Context</em>'.
   * @generated
   */
  IntegrationIntegrationContext createIntegrationIntegrationContext();

  /**
   * Returns a new object of class '<em>Integration TS Node Connection</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration TS Node Connection</em>'.
   * @generated
   */
  IntegrationTSNodeConnection createIntegrationTSNodeConnection();

  /**
   * Returns a new object of class '<em>Integration TS Node Port Base</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration TS Node Port Base</em>'.
   * @generated
   */
  IntegrationTSNodePortBase createIntegrationTSNodePortBase();

  /**
   * Returns a new object of class '<em>Integration Uo PInstance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Uo PInstance</em>'.
   * @generated
   */
  IntegrationUoPInstance createIntegrationUoPInstance();

  /**
   * Returns a new object of class '<em>Integration Uo PInput End Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Uo PInput End Point</em>'.
   * @generated
   */
  IntegrationUoPInputEndPoint createIntegrationUoPInputEndPoint();

  /**
   * Returns a new object of class '<em>Integration Uo POutput End Point</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Uo POutput End Point</em>'.
   * @generated
   */
  IntegrationUoPOutputEndPoint createIntegrationUoPOutputEndPoint();

  /**
   * Returns a new object of class '<em>Integration Transport Node</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Transport Node</em>'.
   * @generated
   */
  IntegrationTransportNode createIntegrationTransportNode();

  /**
   * Returns a new object of class '<em>Integration TS Node Input Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration TS Node Input Port</em>'.
   * @generated
   */
  IntegrationTSNodeInputPort createIntegrationTSNodeInputPort();

  /**
   * Returns a new object of class '<em>Integration TS Node Output Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration TS Node Output Port</em>'.
   * @generated
   */
  IntegrationTSNodeOutputPort createIntegrationTSNodeOutputPort();

  /**
   * Returns a new object of class '<em>Integration View Aggregation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Aggregation</em>'.
   * @generated
   */
  IntegrationViewAggregation createIntegrationViewAggregation();

  /**
   * Returns a new object of class '<em>Integration View Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Filter</em>'.
   * @generated
   */
  IntegrationViewFilter createIntegrationViewFilter();

  /**
   * Returns a new object of class '<em>Integration View Source</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Source</em>'.
   * @generated
   */
  IntegrationViewSource createIntegrationViewSource();

  /**
   * Returns a new object of class '<em>Integration View Sink</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Sink</em>'.
   * @generated
   */
  IntegrationViewSink createIntegrationViewSink();

  /**
   * Returns a new object of class '<em>Integration View Transformation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Transformation</em>'.
   * @generated
   */
  IntegrationViewTransformation createIntegrationViewTransformation();

  /**
   * Returns a new object of class '<em>Integration View Transporter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration View Transporter</em>'.
   * @generated
   */
  IntegrationViewTransporter createIntegrationViewTransporter();

  /**
   * Returns a new object of class '<em>Integration Transport Channel</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Integration Transport Channel</em>'.
   * @generated
   */
  IntegrationTransportChannel createIntegrationTransportChannel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  FacePackage getFacePackage();

} //FaceFactory
