/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration TS Node Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.IntegrationTSNodeConnection#getSource <em>Source</em>}</li>
 *   <li>{@link com.epistimis.face.face.IntegrationTSNodeConnection#getDestination <em>Destination</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodeConnection()
 * @model
 * @generated
 */
public interface IntegrationTSNodeConnection extends EObject
{
  /**
   * Returns the value of the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' reference.
   * @see #setSource(IntegrationTSNodePortBase)
   * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodeConnection_Source()
   * @model
   * @generated
   */
  IntegrationTSNodePortBase getSource();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.IntegrationTSNodeConnection#getSource <em>Source</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' reference.
   * @see #getSource()
   * @generated
   */
  void setSource(IntegrationTSNodePortBase value);

  /**
   * Returns the value of the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Destination</em>' reference.
   * @see #setDestination(IntegrationTSNodePortBase)
   * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodeConnection_Destination()
   * @model
   * @generated
   */
  IntegrationTSNodePortBase getDestination();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.IntegrationTSNodeConnection#getDestination <em>Destination</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Destination</em>' reference.
   * @see #getDestination()
   * @generated
   */
  void setDestination(IntegrationTSNodePortBase value);

} // IntegrationTSNodeConnection
