/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration TS Node Port Base</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodePortBase()
 * @model
 * @generated
 */
public interface IntegrationTSNodePortBase extends EObject
{
} // IntegrationTSNodePortBase
