/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration Transport Node</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.IntegrationTransportNode#getInPort <em>In Port</em>}</li>
 *   <li>{@link com.epistimis.face.face.IntegrationTransportNode#getOutPort <em>Out Port</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getIntegrationTransportNode()
 * @model
 * @generated
 */
public interface IntegrationTransportNode extends FaceElement
{
  /**
   * Returns the value of the '<em><b>In Port</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.face.face.IntegrationTSNodeInputPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In Port</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getIntegrationTransportNode_InPort()
   * @model containment="true"
   * @generated
   */
  EList<IntegrationTSNodeInputPort> getInPort();

  /**
   * Returns the value of the '<em><b>Out Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Out Port</em>' containment reference.
   * @see #setOutPort(IntegrationTSNodeOutputPort)
   * @see com.epistimis.face.face.FacePackage#getIntegrationTransportNode_OutPort()
   * @model containment="true"
   * @generated
   */
  IntegrationTSNodeOutputPort getOutPort();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.IntegrationTransportNode#getOutPort <em>Out Port</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Out Port</em>' containment reference.
   * @see #getOutPort()
   * @generated
   */
  void setOutPort(IntegrationTSNodeOutputPort value);

} // IntegrationTransportNode
