/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration Uo POutput End Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.IntegrationUoPOutputEndPoint#getConnection <em>Connection</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getIntegrationUoPOutputEndPoint()
 * @model
 * @generated
 */
public interface IntegrationUoPOutputEndPoint extends IntegrationTSNodePortBase
{
  /**
   * Returns the value of the '<em><b>Connection</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connection</em>' reference.
   * @see #setConnection(UopConnection)
   * @see com.epistimis.face.face.FacePackage#getIntegrationUoPOutputEndPoint_Connection()
   * @model
   * @generated
   */
  UopConnection getConnection();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.IntegrationUoPOutputEndPoint#getConnection <em>Connection</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Connection</em>' reference.
   * @see #getConnection()
   * @generated
   */
  void setConnection(UopConnection value);

} // IntegrationUoPOutputEndPoint
