/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Integration TS Node Output Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.IntegrationTSNodeOutputPort#getView <em>View</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodeOutputPort()
 * @model
 * @generated
 */
public interface IntegrationTSNodeOutputPort extends IntegrationTSNodePortBase
{
  /**
   * Returns the value of the '<em><b>View</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>View</em>' reference.
   * @see #setView(UopMessageType)
   * @see com.epistimis.face.face.FacePackage#getIntegrationTSNodeOutputPort_View()
   * @model
   * @generated
   */
  UopMessageType getView();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.IntegrationTSNodeOutputPort#getView <em>View</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>View</em>' reference.
   * @see #getView()
   * @generated
   */
  void setView(UopMessageType value);

} // IntegrationTSNodeOutputPort
