/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Abstract Uo P</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopAbstractUoP#getConnection <em>Connection</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopAbstractUoP()
 * @model
 * @generated
 */
public interface UopAbstractUoP extends UopElement
{
  /**
   * Returns the value of the '<em><b>Connection</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.face.face.UopAbstractConnection}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connection</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getUopAbstractUoP_Connection()
   * @model containment="true"
   * @generated
   */
  EList<UopAbstractConnection> getConnection();

} // UopAbstractUoP
