/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import com.epistimis.uddl.uddl.ConceptualView;
import com.epistimis.uddl.uddl.LogicalView;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Abstract Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopAbstractConnection#getName <em>Name</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopAbstractConnection#getDescription <em>Description</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopAbstractConnection#getConceptualView <em>Conceptual View</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopAbstractConnection#getLogicalView <em>Logical View</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopAbstractConnection()
 * @model
 * @generated
 */
public interface UopAbstractConnection extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.epistimis.face.face.FacePackage#getUopAbstractConnection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopAbstractConnection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.epistimis.face.face.FacePackage#getUopAbstractConnection_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopAbstractConnection#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Conceptual View</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conceptual View</em>' reference.
   * @see #setConceptualView(ConceptualView)
   * @see com.epistimis.face.face.FacePackage#getUopAbstractConnection_ConceptualView()
   * @model
   * @generated
   */
  ConceptualView getConceptualView();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopAbstractConnection#getConceptualView <em>Conceptual View</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conceptual View</em>' reference.
   * @see #getConceptualView()
   * @generated
   */
  void setConceptualView(ConceptualView value);

  /**
   * Returns the value of the '<em><b>Logical View</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical View</em>' reference.
   * @see #setLogicalView(LogicalView)
   * @see com.epistimis.face.face.FacePackage#getUopAbstractConnection_LogicalView()
   * @model
   * @generated
   */
  LogicalView getLogicalView();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopAbstractConnection#getLogicalView <em>Logical View</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical View</em>' reference.
   * @see #getLogicalView()
   * @generated
   */
  void setLogicalView(LogicalView value);

} // UopAbstractConnection
