/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopConnection#getName <em>Name</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopConnection#getDescription <em>Description</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopConnection#getRealizes <em>Realizes</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopConnection#getSynchronizationStyle <em>Synchronization Style</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopConnection#getPeriod <em>Period</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopConnection#getMapsTo <em>Maps To</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopConnection()
 * @model
 * @generated
 */
public interface UopConnection extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Realizes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realizes</em>' reference.
   * @see #setRealizes(UopAbstractConnection)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_Realizes()
   * @model
   * @generated
   */
  UopAbstractConnection getRealizes();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getRealizes <em>Realizes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Realizes</em>' reference.
   * @see #getRealizes()
   * @generated
   */
  void setRealizes(UopAbstractConnection value);

  /**
   * Returns the value of the '<em><b>Synchronization Style</b></em>' attribute.
   * The literals are from the enumeration {@link com.epistimis.face.face.UopSynchronizationStyle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Synchronization Style</em>' attribute.
   * @see com.epistimis.face.face.UopSynchronizationStyle
   * @see #setSynchronizationStyle(UopSynchronizationStyle)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_SynchronizationStyle()
   * @model
   * @generated
   */
  UopSynchronizationStyle getSynchronizationStyle();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getSynchronizationStyle <em>Synchronization Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Synchronization Style</em>' attribute.
   * @see com.epistimis.face.face.UopSynchronizationStyle
   * @see #getSynchronizationStyle()
   * @generated
   */
  void setSynchronizationStyle(UopSynchronizationStyle value);

  /**
   * Returns the value of the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Period</em>' attribute.
   * @see #setPeriod(float)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_Period()
   * @model
   * @generated
   */
  float getPeriod();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getPeriod <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Period</em>' attribute.
   * @see #getPeriod()
   * @generated
   */
  void setPeriod(float value);

  /**
   * Returns the value of the '<em><b>Maps To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Maps To</em>' reference.
   * @see #setMapsTo(IntegrationTransportNode)
   * @see com.epistimis.face.face.FacePackage#getUopConnection_MapsTo()
   * @model
   * @generated
   */
  IntegrationTransportNode getMapsTo();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopConnection#getMapsTo <em>Maps To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Maps To</em>' reference.
   * @see #getMapsTo()
   * @generated
   */
  void setMapsTo(IntegrationTransportNode value);

} // UopConnection
