/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Component Framework</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.face.face.FacePackage#getUopComponentFramework()
 * @model
 * @generated
 */
public interface UopComponentFramework extends UopSupportingComponent
{
} // UopComponentFramework
