/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Client Server Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopClientServerConnection#getRequestType <em>Request Type</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopClientServerConnection#getResponseType <em>Response Type</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopClientServerConnection#getRole <em>Role</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopClientServerConnection()
 * @model
 * @generated
 */
public interface UopClientServerConnection extends UopConnection
{
  /**
   * Returns the value of the '<em><b>Request Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Request Type</em>' reference.
   * @see #setRequestType(UopMessageType)
   * @see com.epistimis.face.face.FacePackage#getUopClientServerConnection_RequestType()
   * @model
   * @generated
   */
  UopMessageType getRequestType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopClientServerConnection#getRequestType <em>Request Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Request Type</em>' reference.
   * @see #getRequestType()
   * @generated
   */
  void setRequestType(UopMessageType value);

  /**
   * Returns the value of the '<em><b>Response Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Response Type</em>' reference.
   * @see #setResponseType(UopMessageType)
   * @see com.epistimis.face.face.FacePackage#getUopClientServerConnection_ResponseType()
   * @model
   * @generated
   */
  UopMessageType getResponseType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopClientServerConnection#getResponseType <em>Response Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Response Type</em>' reference.
   * @see #getResponseType()
   * @generated
   */
  void setResponseType(UopMessageType value);

  /**
   * Returns the value of the '<em><b>Role</b></em>' attribute.
   * The literals are from the enumeration {@link com.epistimis.face.face.UoPClientServerRole}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role</em>' attribute.
   * @see com.epistimis.face.face.UoPClientServerRole
   * @see #setRole(UoPClientServerRole)
   * @see com.epistimis.face.face.FacePackage#getUopClientServerConnection_Role()
   * @model
   * @generated
   */
  UoPClientServerRole getRole();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopClientServerConnection#getRole <em>Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role</em>' attribute.
   * @see com.epistimis.face.face.UoPClientServerRole
   * @see #getRole()
   * @generated
   */
  void setRole(UoPClientServerRole value);

} // UopClientServerConnection
