/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import com.epistimis.uddl.uddl.LogicalCompositeQuery;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Composite Template</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopCompositeTemplate#getRealizes <em>Realizes</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopCompositeTemplate#isIsUnion <em>Is Union</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopCompositeTemplate#getComposition <em>Composition</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopCompositeTemplate()
 * @model
 * @generated
 */
public interface UopCompositeTemplate extends UopMessageType
{
  /**
   * Returns the value of the '<em><b>Realizes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realizes</em>' reference.
   * @see #setRealizes(LogicalCompositeQuery)
   * @see com.epistimis.face.face.FacePackage#getUopCompositeTemplate_Realizes()
   * @model
   * @generated
   */
  LogicalCompositeQuery getRealizes();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopCompositeTemplate#getRealizes <em>Realizes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Realizes</em>' reference.
   * @see #getRealizes()
   * @generated
   */
  void setRealizes(LogicalCompositeQuery value);

  /**
   * Returns the value of the '<em><b>Is Union</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Union</em>' attribute.
   * @see #setIsUnion(boolean)
   * @see com.epistimis.face.face.FacePackage#getUopCompositeTemplate_IsUnion()
   * @model
   * @generated
   */
  boolean isIsUnion();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopCompositeTemplate#isIsUnion <em>Is Union</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Union</em>' attribute.
   * @see #isIsUnion()
   * @generated
   */
  void setIsUnion(boolean value);

  /**
   * Returns the value of the '<em><b>Composition</b></em>' containment reference list.
   * The list contents are of type {@link com.epistimis.face.face.UopTemplateComposition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Composition</em>' containment reference list.
   * @see com.epistimis.face.face.FacePackage#getUopCompositeTemplate_Composition()
   * @model containment="true"
   * @generated
   */
  EList<UopTemplateComposition> getComposition();

} // UopCompositeTemplate
