/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.epistimis.face.face.FacePackage#getUopElement()
 * @model
 * @generated
 */
public interface UopElement extends FaceElement
{
} // UopElement
