/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Uop Face Profile</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see com.epistimis.face.face.FacePackage#getUopFaceProfile()
 * @model
 * @generated
 */
public enum UopFaceProfile implements Enumerator
{
  /**
   * The '<em><b>GENERAL PURPOSE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GENERAL_PURPOSE_VALUE
   * @generated
   * @ordered
   */
  GENERAL_PURPOSE(0, "GENERAL_PURPOSE", "GeneralPurpose"),

  /**
   * The '<em><b>SECURITY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY_VALUE
   * @generated
   * @ordered
   */
  SECURITY(1, "SECURITY", "Security"),

  /**
   * The '<em><b>SAFETY BASE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SAFETY_BASE_VALUE
   * @generated
   * @ordered
   */
  SAFETY_BASE(2, "SAFETY_BASE", "SafetyBase"),

  /**
   * The '<em><b>SAFETY EXTENDED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SAFETY_EXTENDED_VALUE
   * @generated
   * @ordered
   */
  SAFETY_EXTENDED(3, "SAFETY_EXTENDED", "SafetyExtended");

  /**
   * The '<em><b>GENERAL PURPOSE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GENERAL_PURPOSE
   * @model literal="GeneralPurpose"
   * @generated
   * @ordered
   */
  public static final int GENERAL_PURPOSE_VALUE = 0;

  /**
   * The '<em><b>SECURITY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY
   * @model literal="Security"
   * @generated
   * @ordered
   */
  public static final int SECURITY_VALUE = 1;

  /**
   * The '<em><b>SAFETY BASE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SAFETY_BASE
   * @model literal="SafetyBase"
   * @generated
   * @ordered
   */
  public static final int SAFETY_BASE_VALUE = 2;

  /**
   * The '<em><b>SAFETY EXTENDED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SAFETY_EXTENDED
   * @model literal="SafetyExtended"
   * @generated
   * @ordered
   */
  public static final int SAFETY_EXTENDED_VALUE = 3;

  /**
   * An array of all the '<em><b>Uop Face Profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final UopFaceProfile[] VALUES_ARRAY =
    new UopFaceProfile[]
    {
      GENERAL_PURPOSE,
      SECURITY,
      SAFETY_BASE,
      SAFETY_EXTENDED,
    };

  /**
   * A public read-only list of all the '<em><b>Uop Face Profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<UopFaceProfile> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Uop Face Profile</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static UopFaceProfile get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      UopFaceProfile result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Uop Face Profile</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static UopFaceProfile getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      UopFaceProfile result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Uop Face Profile</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static UopFaceProfile get(int value)
  {
    switch (value)
    {
      case GENERAL_PURPOSE_VALUE: return GENERAL_PURPOSE;
      case SECURITY_VALUE: return SECURITY;
      case SAFETY_BASE_VALUE: return SAFETY_BASE;
      case SAFETY_EXTENDED_VALUE: return SAFETY_EXTENDED;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private UopFaceProfile(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //UopFaceProfile
