/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Life Cycle Management Port</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopLifeCycleManagementPort#getMessageExchangeType <em>Message Exchange Type</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopLifeCycleManagementPort#getLcmMessageType <em>Lcm Message Type</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopLifeCycleManagementPort()
 * @model
 * @generated
 */
public interface UopLifeCycleManagementPort extends EObject
{
  /**
   * Returns the value of the '<em><b>Message Exchange Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.epistimis.face.face.UopMessageExchangeType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message Exchange Type</em>' attribute.
   * @see com.epistimis.face.face.UopMessageExchangeType
   * @see #setMessageExchangeType(UopMessageExchangeType)
   * @see com.epistimis.face.face.FacePackage#getUopLifeCycleManagementPort_MessageExchangeType()
   * @model
   * @generated
   */
  UopMessageExchangeType getMessageExchangeType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopLifeCycleManagementPort#getMessageExchangeType <em>Message Exchange Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message Exchange Type</em>' attribute.
   * @see com.epistimis.face.face.UopMessageExchangeType
   * @see #getMessageExchangeType()
   * @generated
   */
  void setMessageExchangeType(UopMessageExchangeType value);

  /**
   * Returns the value of the '<em><b>Lcm Message Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lcm Message Type</em>' reference.
   * @see #setLcmMessageType(UopMessageType)
   * @see com.epistimis.face.face.FacePackage#getUopLifeCycleManagementPort_LcmMessageType()
   * @model
   * @generated
   */
  UopMessageType getLcmMessageType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopLifeCycleManagementPort#getLcmMessageType <em>Lcm Message Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lcm Message Type</em>' reference.
   * @see #getLcmMessageType()
   * @generated
   */
  void setLcmMessageType(UopMessageType value);

} // UopLifeCycleManagementPort
