/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import com.epistimis.uddl.uddl.PlatformQuery;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Template</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopTemplate#getSpecification <em>Specification</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopTemplate#getBoundQuery <em>Bound Query</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopTemplate#getEffectiveQuery <em>Effective Query</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopTemplate()
 * @model
 * @generated
 */
public interface UopTemplate extends UopMessageType
{
  /**
   * Returns the value of the '<em><b>Specification</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specification</em>' attribute.
   * @see #setSpecification(String)
   * @see com.epistimis.face.face.FacePackage#getUopTemplate_Specification()
   * @model
   * @generated
   */
  String getSpecification();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplate#getSpecification <em>Specification</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Specification</em>' attribute.
   * @see #getSpecification()
   * @generated
   */
  void setSpecification(String value);

  /**
   * Returns the value of the '<em><b>Bound Query</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bound Query</em>' reference.
   * @see #setBoundQuery(PlatformQuery)
   * @see com.epistimis.face.face.FacePackage#getUopTemplate_BoundQuery()
   * @model
   * @generated
   */
  PlatformQuery getBoundQuery();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplate#getBoundQuery <em>Bound Query</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bound Query</em>' reference.
   * @see #getBoundQuery()
   * @generated
   */
  void setBoundQuery(PlatformQuery value);

  /**
   * Returns the value of the '<em><b>Effective Query</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Effective Query</em>' reference.
   * @see #setEffectiveQuery(PlatformQuery)
   * @see com.epistimis.face.face.FacePackage#getUopTemplate_EffectiveQuery()
   * @model
   * @generated
   */
  PlatformQuery getEffectiveQuery();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplate#getEffectiveQuery <em>Effective Query</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Effective Query</em>' reference.
   * @see #getEffectiveQuery()
   * @generated
   */
  void setEffectiveQuery(PlatformQuery value);

} // UopTemplate
