/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import com.epistimis.uddl.uddl.LogicalQueryComposition;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Template Composition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopTemplateComposition#getType <em>Type</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopTemplateComposition#getRolename <em>Rolename</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopTemplateComposition#getRealizes <em>Realizes</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopTemplateComposition()
 * @model
 * @generated
 */
public interface UopTemplateComposition extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(UopMessageType)
   * @see com.epistimis.face.face.FacePackage#getUopTemplateComposition_Type()
   * @model
   * @generated
   */
  UopMessageType getType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplateComposition#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(UopMessageType value);

  /**
   * Returns the value of the '<em><b>Rolename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rolename</em>' attribute.
   * @see #setRolename(String)
   * @see com.epistimis.face.face.FacePackage#getUopTemplateComposition_Rolename()
   * @model
   * @generated
   */
  String getRolename();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplateComposition#getRolename <em>Rolename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rolename</em>' attribute.
   * @see #getRolename()
   * @generated
   */
  void setRolename(String value);

  /**
   * Returns the value of the '<em><b>Realizes</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Realizes</em>' reference.
   * @see #setRealizes(LogicalQueryComposition)
   * @see com.epistimis.face.face.FacePackage#getUopTemplateComposition_Realizes()
   * @model
   * @generated
   */
  LogicalQueryComposition getRealizes();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopTemplateComposition#getRealizes <em>Realizes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Realizes</em>' reference.
   * @see #getRealizes()
   * @generated
   */
  void setRealizes(LogicalQueryComposition value);

} // UopTemplateComposition
