/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uop Thread</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.UopThread#getPeriod <em>Period</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopThread#getTimeCapacity <em>Time Capacity</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopThread#getRelativePriority <em>Relative Priority</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopThread#getRelativeCoreAffinity <em>Relative Core Affinity</em>}</li>
 *   <li>{@link com.epistimis.face.face.UopThread#getThreadType <em>Thread Type</em>}</li>
 * </ul>
 *
 * @see com.epistimis.face.face.FacePackage#getUopThread()
 * @model
 * @generated
 */
public interface UopThread extends EObject
{
  /**
   * Returns the value of the '<em><b>Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Period</em>' attribute.
   * @see #setPeriod(float)
   * @see com.epistimis.face.face.FacePackage#getUopThread_Period()
   * @model
   * @generated
   */
  float getPeriod();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopThread#getPeriod <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Period</em>' attribute.
   * @see #getPeriod()
   * @generated
   */
  void setPeriod(float value);

  /**
   * Returns the value of the '<em><b>Time Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Capacity</em>' attribute.
   * @see #setTimeCapacity(float)
   * @see com.epistimis.face.face.FacePackage#getUopThread_TimeCapacity()
   * @model
   * @generated
   */
  float getTimeCapacity();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopThread#getTimeCapacity <em>Time Capacity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Capacity</em>' attribute.
   * @see #getTimeCapacity()
   * @generated
   */
  void setTimeCapacity(float value);

  /**
   * Returns the value of the '<em><b>Relative Priority</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relative Priority</em>' attribute.
   * @see #setRelativePriority(int)
   * @see com.epistimis.face.face.FacePackage#getUopThread_RelativePriority()
   * @model
   * @generated
   */
  int getRelativePriority();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopThread#getRelativePriority <em>Relative Priority</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relative Priority</em>' attribute.
   * @see #getRelativePriority()
   * @generated
   */
  void setRelativePriority(int value);

  /**
   * Returns the value of the '<em><b>Relative Core Affinity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relative Core Affinity</em>' attribute.
   * @see #setRelativeCoreAffinity(int)
   * @see com.epistimis.face.face.FacePackage#getUopThread_RelativeCoreAffinity()
   * @model
   * @generated
   */
  int getRelativeCoreAffinity();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopThread#getRelativeCoreAffinity <em>Relative Core Affinity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relative Core Affinity</em>' attribute.
   * @see #getRelativeCoreAffinity()
   * @generated
   */
  void setRelativeCoreAffinity(int value);

  /**
   * Returns the value of the '<em><b>Thread Type</b></em>' attribute.
   * The literals are from the enumeration {@link com.epistimis.face.face.UopThreadType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Thread Type</em>' attribute.
   * @see com.epistimis.face.face.UopThreadType
   * @see #setThreadType(UopThreadType)
   * @see com.epistimis.face.face.FacePackage#getUopThread_ThreadType()
   * @model
   * @generated
   */
  UopThreadType getThreadType();

  /**
   * Sets the value of the '{@link com.epistimis.face.face.UopThread#getThreadType <em>Thread Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Thread Type</em>' attribute.
   * @see com.epistimis.face.face.UopThreadType
   * @see #getThreadType()
   * @generated
   */
  void setThreadType(UopThreadType value);

} // UopThread
