/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face.impl;

import com.epistimis.face.face.ArchitectureModel;
import com.epistimis.face.face.FaceElement;
import com.epistimis.face.face.FaceFactory;
import com.epistimis.face.face.FacePackage;
import com.epistimis.face.face.IntegrationElement;
import com.epistimis.face.face.IntegrationIntegrationContext;
import com.epistimis.face.face.IntegrationIntegrationModel;
import com.epistimis.face.face.IntegrationTSNodeConnection;
import com.epistimis.face.face.IntegrationTSNodeInputPort;
import com.epistimis.face.face.IntegrationTSNodeOutputPort;
import com.epistimis.face.face.IntegrationTSNodePortBase;
import com.epistimis.face.face.IntegrationTransportChannel;
import com.epistimis.face.face.IntegrationTransportNode;
import com.epistimis.face.face.IntegrationUoPInputEndPoint;
import com.epistimis.face.face.IntegrationUoPInstance;
import com.epistimis.face.face.IntegrationUoPOutputEndPoint;
import com.epistimis.face.face.IntegrationViewAggregation;
import com.epistimis.face.face.IntegrationViewFilter;
import com.epistimis.face.face.IntegrationViewSink;
import com.epistimis.face.face.IntegrationViewSource;
import com.epistimis.face.face.IntegrationViewTransformation;
import com.epistimis.face.face.IntegrationViewTransporter;
import com.epistimis.face.face.UoPClientServerRole;
import com.epistimis.face.face.UopAbstractConnection;
import com.epistimis.face.face.UopAbstractUoP;
import com.epistimis.face.face.UopClientServerConnection;
import com.epistimis.face.face.UopComponentFramework;
import com.epistimis.face.face.UopCompositeTemplate;
import com.epistimis.face.face.UopConnection;
import com.epistimis.face.face.UopDesignAssuranceLevel;
import com.epistimis.face.face.UopDesignAssuranceStandard;
import com.epistimis.face.face.UopElement;
import com.epistimis.face.face.UopFaceProfile;
import com.epistimis.face.face.UopLanguageRuntime;
import com.epistimis.face.face.UopLifeCycleManagementPort;
import com.epistimis.face.face.UopMessageExchangeType;
import com.epistimis.face.face.UopMessageType;
import com.epistimis.face.face.UopPartitionType;
import com.epistimis.face.face.UopPlatformSpecificComponent;
import com.epistimis.face.face.UopPortableComponent;
import com.epistimis.face.face.UopProgrammingLanguage;
import com.epistimis.face.face.UopPubSubConnection;
import com.epistimis.face.face.UopQueuingConnection;
import com.epistimis.face.face.UopRAMMemoryRequirements;
import com.epistimis.face.face.UopSingleInstanceMessageConnection;
import com.epistimis.face.face.UopSupportingComponent;
import com.epistimis.face.face.UopSynchronizationStyle;
import com.epistimis.face.face.UopTemplate;
import com.epistimis.face.face.UopTemplateComposition;
import com.epistimis.face.face.UopThread;
import com.epistimis.face.face.UopThreadType;
import com.epistimis.face.face.UopUnitOfPortability;
import com.epistimis.face.face.UopUoPModel;

import com.epistimis.uddl.uddl.UddlPackage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class FacePackageImpl extends EPackageImpl implements FacePackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass architectureModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass faceElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopUoPModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopSupportingComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopLanguageRuntimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopComponentFrameworkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopAbstractUoPEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopAbstractConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopUnitOfPortabilityEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopPortableComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopPlatformSpecificComponentEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopThreadEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopRAMMemoryRequirementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopClientServerConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopPubSubConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopQueuingConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopSingleInstanceMessageConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopLifeCycleManagementPortEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopMessageTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopCompositeTemplateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopTemplateCompositionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass uopTemplateEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationIntegrationModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationElementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationIntegrationContextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTSNodeConnectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTSNodePortBaseEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationUoPInstanceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationUoPInputEndPointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationUoPOutputEndPointEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTransportNodeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTSNodeInputPortEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTSNodeOutputPortEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewAggregationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewFilterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewSourceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewSinkEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewTransformationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationViewTransporterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass integrationTransportChannelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uoPClientServerRoleEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopFaceProfileEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopDesignAssuranceLevelEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopDesignAssuranceStandardEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopMessageExchangeTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopPartitionTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopProgrammingLanguageEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopSynchronizationStyleEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum uopThreadTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see com.epistimis.face.face.FacePackage#eNS_URI
   * @see #init()
   * @generated
   */
  private FacePackageImpl()
  {
    super(eNS_URI, FaceFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link FacePackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static FacePackage init()
  {
    if (isInited) return (FacePackage)EPackage.Registry.INSTANCE.getEPackage(FacePackage.eNS_URI);

    // Obtain or create and register package
    Object registeredFacePackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    FacePackageImpl theFacePackage = registeredFacePackage instanceof FacePackageImpl ? (FacePackageImpl)registeredFacePackage : new FacePackageImpl();

    isInited = true;

    // Initialize simple dependencies
    UddlPackage.eINSTANCE.eClass();

    // Create package meta-data objects
    theFacePackage.createPackageContents();

    // Initialize created meta-data
    theFacePackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theFacePackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(FacePackage.eNS_URI, theFacePackage);
    return theFacePackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArchitectureModel()
  {
    return architectureModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitectureModel_Dm()
  {
    return (EReference)architectureModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitectureModel_Um()
  {
    return (EReference)architectureModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getArchitectureModel_Im()
  {
    return (EReference)architectureModelEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFaceElement()
  {
    return faceElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFaceElement_Name()
  {
    return (EAttribute)faceElementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFaceElement_Description()
  {
    return (EAttribute)faceElementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopUoPModel()
  {
    return uopUoPModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUoPModel_Um()
  {
    return (EReference)uopUoPModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUoPModel_Element()
  {
    return (EReference)uopUoPModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopElement()
  {
    return uopElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopSupportingComponent()
  {
    return uopSupportingComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopSupportingComponent_Version()
  {
    return (EAttribute)uopSupportingComponentEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopLanguageRuntime()
  {
    return uopLanguageRuntimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopComponentFramework()
  {
    return uopComponentFrameworkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopAbstractUoP()
  {
    return uopAbstractUoPEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopAbstractUoP_Connection()
  {
    return (EReference)uopAbstractUoPEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopAbstractConnection()
  {
    return uopAbstractConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopAbstractConnection_Name()
  {
    return (EAttribute)uopAbstractConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopAbstractConnection_Description()
  {
    return (EAttribute)uopAbstractConnectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopAbstractConnection_ConceptualView()
  {
    return (EReference)uopAbstractConnectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopAbstractConnection_LogicalView()
  {
    return (EReference)uopAbstractConnectionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopUnitOfPortability()
  {
    return uopUnitOfPortabilityEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_Realizes()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopUnitOfPortability_TransportAPILanguage()
  {
    return (EAttribute)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopUnitOfPortability_PartitionType()
  {
    return (EAttribute)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopUnitOfPortability_FaceProfile()
  {
    return (EAttribute)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopUnitOfPortability_DesignAssuranceLevel()
  {
    return (EAttribute)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopUnitOfPortability_DesignAssuranceStandard()
  {
    return (EAttribute)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_MemoryRequirements()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_Thread()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(7);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_SupportingComponent()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(8);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_Connection()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(9);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_LcmPort()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(10);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopUnitOfPortability_ImplementedBy()
  {
    return (EReference)uopUnitOfPortabilityEClass.getEStructuralFeatures().get(11);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopPortableComponent()
  {
    return uopPortableComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopPlatformSpecificComponent()
  {
    return uopPlatformSpecificComponentEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopThread()
  {
    return uopThreadEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopThread_Period()
  {
    return (EAttribute)uopThreadEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopThread_TimeCapacity()
  {
    return (EAttribute)uopThreadEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopThread_RelativePriority()
  {
    return (EAttribute)uopThreadEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopThread_RelativeCoreAffinity()
  {
    return (EAttribute)uopThreadEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopThread_ThreadType()
  {
    return (EAttribute)uopThreadEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopRAMMemoryRequirements()
  {
    return uopRAMMemoryRequirementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_HeapStackMin()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_HeapStackTypical()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_HeapStackMax()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_TextMax()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_RoDataMax()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_DataMax()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopRAMMemoryRequirements_BssMax()
  {
    return (EAttribute)uopRAMMemoryRequirementsEClass.getEStructuralFeatures().get(6);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopConnection()
  {
    return uopConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopConnection_Name()
  {
    return (EAttribute)uopConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopConnection_Description()
  {
    return (EAttribute)uopConnectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopConnection_Realizes()
  {
    return (EReference)uopConnectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopConnection_SynchronizationStyle()
  {
    return (EAttribute)uopConnectionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopConnection_Period()
  {
    return (EAttribute)uopConnectionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopConnection_MapsTo()
  {
    return (EReference)uopConnectionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopClientServerConnection()
  {
    return uopClientServerConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopClientServerConnection_RequestType()
  {
    return (EReference)uopClientServerConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopClientServerConnection_ResponseType()
  {
    return (EReference)uopClientServerConnectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopClientServerConnection_Role()
  {
    return (EAttribute)uopClientServerConnectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopPubSubConnection()
  {
    return uopPubSubConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopPubSubConnection_MessageExchangeType()
  {
    return (EAttribute)uopPubSubConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopPubSubConnection_MessageType()
  {
    return (EReference)uopPubSubConnectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopQueuingConnection()
  {
    return uopQueuingConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopQueuingConnection_Depth()
  {
    return (EAttribute)uopQueuingConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopSingleInstanceMessageConnection()
  {
    return uopSingleInstanceMessageConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopLifeCycleManagementPort()
  {
    return uopLifeCycleManagementPortEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopLifeCycleManagementPort_MessageExchangeType()
  {
    return (EAttribute)uopLifeCycleManagementPortEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopLifeCycleManagementPort_LcmMessageType()
  {
    return (EReference)uopLifeCycleManagementPortEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopMessageType()
  {
    return uopMessageTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopCompositeTemplate()
  {
    return uopCompositeTemplateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopCompositeTemplate_Realizes()
  {
    return (EReference)uopCompositeTemplateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopCompositeTemplate_IsUnion()
  {
    return (EAttribute)uopCompositeTemplateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopCompositeTemplate_Composition()
  {
    return (EReference)uopCompositeTemplateEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopTemplateComposition()
  {
    return uopTemplateCompositionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopTemplateComposition_Type()
  {
    return (EReference)uopTemplateCompositionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopTemplateComposition_Rolename()
  {
    return (EAttribute)uopTemplateCompositionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopTemplateComposition_Realizes()
  {
    return (EReference)uopTemplateCompositionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getUopTemplate()
  {
    return uopTemplateEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getUopTemplate_Specification()
  {
    return (EAttribute)uopTemplateEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopTemplate_BoundQuery()
  {
    return (EReference)uopTemplateEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getUopTemplate_EffectiveQuery()
  {
    return (EReference)uopTemplateEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationIntegrationModel()
  {
    return integrationIntegrationModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationIntegrationModel_Im()
  {
    return (EReference)integrationIntegrationModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationIntegrationModel_Element()
  {
    return (EReference)integrationIntegrationModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationElement()
  {
    return integrationElementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationIntegrationContext()
  {
    return integrationIntegrationContextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationIntegrationContext_Node()
  {
    return (EReference)integrationIntegrationContextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationIntegrationContext_Connection()
  {
    return (EReference)integrationIntegrationContextEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTSNodeConnection()
  {
    return integrationTSNodeConnectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTSNodeConnection_Source()
  {
    return (EReference)integrationTSNodeConnectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTSNodeConnection_Destination()
  {
    return (EReference)integrationTSNodeConnectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTSNodePortBase()
  {
    return integrationTSNodePortBaseEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationUoPInstance()
  {
    return integrationUoPInstanceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationUoPInstance_Realizes()
  {
    return (EReference)integrationUoPInstanceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntegrationUoPInstance_ConfigurationURI()
  {
    return (EAttribute)integrationUoPInstanceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationUoPInstance_Input()
  {
    return (EReference)integrationUoPInstanceEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationUoPInstance_Output()
  {
    return (EReference)integrationUoPInstanceEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationUoPInputEndPoint()
  {
    return integrationUoPInputEndPointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationUoPInputEndPoint_Connection()
  {
    return (EReference)integrationUoPInputEndPointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationUoPOutputEndPoint()
  {
    return integrationUoPOutputEndPointEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationUoPOutputEndPoint_Connection()
  {
    return (EReference)integrationUoPOutputEndPointEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTransportNode()
  {
    return integrationTransportNodeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTransportNode_InPort()
  {
    return (EReference)integrationTransportNodeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTransportNode_OutPort()
  {
    return (EReference)integrationTransportNodeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTSNodeInputPort()
  {
    return integrationTSNodeInputPortEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTSNodeInputPort_View()
  {
    return (EReference)integrationTSNodeInputPortEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTSNodeOutputPort()
  {
    return integrationTSNodeOutputPortEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationTSNodeOutputPort_View()
  {
    return (EReference)integrationTSNodeOutputPortEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewAggregation()
  {
    return integrationViewAggregationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewFilter()
  {
    return integrationViewFilterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewSource()
  {
    return integrationViewSourceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewSink()
  {
    return integrationViewSinkEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewTransformation()
  {
    return integrationViewTransformationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationViewTransporter()
  {
    return integrationViewTransporterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntegrationViewTransporter_Channel()
  {
    return (EReference)integrationViewTransporterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntegrationTransportChannel()
  {
    return integrationTransportChannelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUoPClientServerRole()
  {
    return uoPClientServerRoleEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopFaceProfile()
  {
    return uopFaceProfileEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopDesignAssuranceLevel()
  {
    return uopDesignAssuranceLevelEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopDesignAssuranceStandard()
  {
    return uopDesignAssuranceStandardEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopMessageExchangeType()
  {
    return uopMessageExchangeTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopPartitionType()
  {
    return uopPartitionTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopProgrammingLanguage()
  {
    return uopProgrammingLanguageEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopSynchronizationStyle()
  {
    return uopSynchronizationStyleEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getUopThreadType()
  {
    return uopThreadTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FaceFactory getFaceFactory()
  {
    return (FaceFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    architectureModelEClass = createEClass(ARCHITECTURE_MODEL);
    createEReference(architectureModelEClass, ARCHITECTURE_MODEL__DM);
    createEReference(architectureModelEClass, ARCHITECTURE_MODEL__UM);
    createEReference(architectureModelEClass, ARCHITECTURE_MODEL__IM);

    faceElementEClass = createEClass(FACE_ELEMENT);
    createEAttribute(faceElementEClass, FACE_ELEMENT__NAME);
    createEAttribute(faceElementEClass, FACE_ELEMENT__DESCRIPTION);

    uopUoPModelEClass = createEClass(UOP_UO_PMODEL);
    createEReference(uopUoPModelEClass, UOP_UO_PMODEL__UM);
    createEReference(uopUoPModelEClass, UOP_UO_PMODEL__ELEMENT);

    uopElementEClass = createEClass(UOP_ELEMENT);

    uopSupportingComponentEClass = createEClass(UOP_SUPPORTING_COMPONENT);
    createEAttribute(uopSupportingComponentEClass, UOP_SUPPORTING_COMPONENT__VERSION);

    uopLanguageRuntimeEClass = createEClass(UOP_LANGUAGE_RUNTIME);

    uopComponentFrameworkEClass = createEClass(UOP_COMPONENT_FRAMEWORK);

    uopAbstractUoPEClass = createEClass(UOP_ABSTRACT_UO_P);
    createEReference(uopAbstractUoPEClass, UOP_ABSTRACT_UO_P__CONNECTION);

    uopAbstractConnectionEClass = createEClass(UOP_ABSTRACT_CONNECTION);
    createEAttribute(uopAbstractConnectionEClass, UOP_ABSTRACT_CONNECTION__NAME);
    createEAttribute(uopAbstractConnectionEClass, UOP_ABSTRACT_CONNECTION__DESCRIPTION);
    createEReference(uopAbstractConnectionEClass, UOP_ABSTRACT_CONNECTION__CONCEPTUAL_VIEW);
    createEReference(uopAbstractConnectionEClass, UOP_ABSTRACT_CONNECTION__LOGICAL_VIEW);

    uopUnitOfPortabilityEClass = createEClass(UOP_UNIT_OF_PORTABILITY);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__REALIZES);
    createEAttribute(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__TRANSPORT_API_LANGUAGE);
    createEAttribute(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__PARTITION_TYPE);
    createEAttribute(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__FACE_PROFILE);
    createEAttribute(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__DESIGN_ASSURANCE_LEVEL);
    createEAttribute(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__DESIGN_ASSURANCE_STANDARD);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__MEMORY_REQUIREMENTS);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__THREAD);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__SUPPORTING_COMPONENT);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__CONNECTION);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__LCM_PORT);
    createEReference(uopUnitOfPortabilityEClass, UOP_UNIT_OF_PORTABILITY__IMPLEMENTED_BY);

    uopPortableComponentEClass = createEClass(UOP_PORTABLE_COMPONENT);

    uopPlatformSpecificComponentEClass = createEClass(UOP_PLATFORM_SPECIFIC_COMPONENT);

    uopThreadEClass = createEClass(UOP_THREAD);
    createEAttribute(uopThreadEClass, UOP_THREAD__PERIOD);
    createEAttribute(uopThreadEClass, UOP_THREAD__TIME_CAPACITY);
    createEAttribute(uopThreadEClass, UOP_THREAD__RELATIVE_PRIORITY);
    createEAttribute(uopThreadEClass, UOP_THREAD__RELATIVE_CORE_AFFINITY);
    createEAttribute(uopThreadEClass, UOP_THREAD__THREAD_TYPE);

    uopRAMMemoryRequirementsEClass = createEClass(UOP_RAM_MEMORY_REQUIREMENTS);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__HEAP_STACK_MIN);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__HEAP_STACK_TYPICAL);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__HEAP_STACK_MAX);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__TEXT_MAX);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__RO_DATA_MAX);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__DATA_MAX);
    createEAttribute(uopRAMMemoryRequirementsEClass, UOP_RAM_MEMORY_REQUIREMENTS__BSS_MAX);

    uopConnectionEClass = createEClass(UOP_CONNECTION);
    createEAttribute(uopConnectionEClass, UOP_CONNECTION__NAME);
    createEAttribute(uopConnectionEClass, UOP_CONNECTION__DESCRIPTION);
    createEReference(uopConnectionEClass, UOP_CONNECTION__REALIZES);
    createEAttribute(uopConnectionEClass, UOP_CONNECTION__SYNCHRONIZATION_STYLE);
    createEAttribute(uopConnectionEClass, UOP_CONNECTION__PERIOD);
    createEReference(uopConnectionEClass, UOP_CONNECTION__MAPS_TO);

    uopClientServerConnectionEClass = createEClass(UOP_CLIENT_SERVER_CONNECTION);
    createEReference(uopClientServerConnectionEClass, UOP_CLIENT_SERVER_CONNECTION__REQUEST_TYPE);
    createEReference(uopClientServerConnectionEClass, UOP_CLIENT_SERVER_CONNECTION__RESPONSE_TYPE);
    createEAttribute(uopClientServerConnectionEClass, UOP_CLIENT_SERVER_CONNECTION__ROLE);

    uopPubSubConnectionEClass = createEClass(UOP_PUB_SUB_CONNECTION);
    createEAttribute(uopPubSubConnectionEClass, UOP_PUB_SUB_CONNECTION__MESSAGE_EXCHANGE_TYPE);
    createEReference(uopPubSubConnectionEClass, UOP_PUB_SUB_CONNECTION__MESSAGE_TYPE);

    uopQueuingConnectionEClass = createEClass(UOP_QUEUING_CONNECTION);
    createEAttribute(uopQueuingConnectionEClass, UOP_QUEUING_CONNECTION__DEPTH);

    uopSingleInstanceMessageConnectionEClass = createEClass(UOP_SINGLE_INSTANCE_MESSAGE_CONNECTION);

    uopLifeCycleManagementPortEClass = createEClass(UOP_LIFE_CYCLE_MANAGEMENT_PORT);
    createEAttribute(uopLifeCycleManagementPortEClass, UOP_LIFE_CYCLE_MANAGEMENT_PORT__MESSAGE_EXCHANGE_TYPE);
    createEReference(uopLifeCycleManagementPortEClass, UOP_LIFE_CYCLE_MANAGEMENT_PORT__LCM_MESSAGE_TYPE);

    uopMessageTypeEClass = createEClass(UOP_MESSAGE_TYPE);

    uopCompositeTemplateEClass = createEClass(UOP_COMPOSITE_TEMPLATE);
    createEReference(uopCompositeTemplateEClass, UOP_COMPOSITE_TEMPLATE__REALIZES);
    createEAttribute(uopCompositeTemplateEClass, UOP_COMPOSITE_TEMPLATE__IS_UNION);
    createEReference(uopCompositeTemplateEClass, UOP_COMPOSITE_TEMPLATE__COMPOSITION);

    uopTemplateCompositionEClass = createEClass(UOP_TEMPLATE_COMPOSITION);
    createEReference(uopTemplateCompositionEClass, UOP_TEMPLATE_COMPOSITION__TYPE);
    createEAttribute(uopTemplateCompositionEClass, UOP_TEMPLATE_COMPOSITION__ROLENAME);
    createEReference(uopTemplateCompositionEClass, UOP_TEMPLATE_COMPOSITION__REALIZES);

    uopTemplateEClass = createEClass(UOP_TEMPLATE);
    createEAttribute(uopTemplateEClass, UOP_TEMPLATE__SPECIFICATION);
    createEReference(uopTemplateEClass, UOP_TEMPLATE__BOUND_QUERY);
    createEReference(uopTemplateEClass, UOP_TEMPLATE__EFFECTIVE_QUERY);

    integrationIntegrationModelEClass = createEClass(INTEGRATION_INTEGRATION_MODEL);
    createEReference(integrationIntegrationModelEClass, INTEGRATION_INTEGRATION_MODEL__IM);
    createEReference(integrationIntegrationModelEClass, INTEGRATION_INTEGRATION_MODEL__ELEMENT);

    integrationElementEClass = createEClass(INTEGRATION_ELEMENT);

    integrationIntegrationContextEClass = createEClass(INTEGRATION_INTEGRATION_CONTEXT);
    createEReference(integrationIntegrationContextEClass, INTEGRATION_INTEGRATION_CONTEXT__NODE);
    createEReference(integrationIntegrationContextEClass, INTEGRATION_INTEGRATION_CONTEXT__CONNECTION);

    integrationTSNodeConnectionEClass = createEClass(INTEGRATION_TS_NODE_CONNECTION);
    createEReference(integrationTSNodeConnectionEClass, INTEGRATION_TS_NODE_CONNECTION__SOURCE);
    createEReference(integrationTSNodeConnectionEClass, INTEGRATION_TS_NODE_CONNECTION__DESTINATION);

    integrationTSNodePortBaseEClass = createEClass(INTEGRATION_TS_NODE_PORT_BASE);

    integrationUoPInstanceEClass = createEClass(INTEGRATION_UO_PINSTANCE);
    createEReference(integrationUoPInstanceEClass, INTEGRATION_UO_PINSTANCE__REALIZES);
    createEAttribute(integrationUoPInstanceEClass, INTEGRATION_UO_PINSTANCE__CONFIGURATION_URI);
    createEReference(integrationUoPInstanceEClass, INTEGRATION_UO_PINSTANCE__INPUT);
    createEReference(integrationUoPInstanceEClass, INTEGRATION_UO_PINSTANCE__OUTPUT);

    integrationUoPInputEndPointEClass = createEClass(INTEGRATION_UO_PINPUT_END_POINT);
    createEReference(integrationUoPInputEndPointEClass, INTEGRATION_UO_PINPUT_END_POINT__CONNECTION);

    integrationUoPOutputEndPointEClass = createEClass(INTEGRATION_UO_POUTPUT_END_POINT);
    createEReference(integrationUoPOutputEndPointEClass, INTEGRATION_UO_POUTPUT_END_POINT__CONNECTION);

    integrationTransportNodeEClass = createEClass(INTEGRATION_TRANSPORT_NODE);
    createEReference(integrationTransportNodeEClass, INTEGRATION_TRANSPORT_NODE__IN_PORT);
    createEReference(integrationTransportNodeEClass, INTEGRATION_TRANSPORT_NODE__OUT_PORT);

    integrationTSNodeInputPortEClass = createEClass(INTEGRATION_TS_NODE_INPUT_PORT);
    createEReference(integrationTSNodeInputPortEClass, INTEGRATION_TS_NODE_INPUT_PORT__VIEW);

    integrationTSNodeOutputPortEClass = createEClass(INTEGRATION_TS_NODE_OUTPUT_PORT);
    createEReference(integrationTSNodeOutputPortEClass, INTEGRATION_TS_NODE_OUTPUT_PORT__VIEW);

    integrationViewAggregationEClass = createEClass(INTEGRATION_VIEW_AGGREGATION);

    integrationViewFilterEClass = createEClass(INTEGRATION_VIEW_FILTER);

    integrationViewSourceEClass = createEClass(INTEGRATION_VIEW_SOURCE);

    integrationViewSinkEClass = createEClass(INTEGRATION_VIEW_SINK);

    integrationViewTransformationEClass = createEClass(INTEGRATION_VIEW_TRANSFORMATION);

    integrationViewTransporterEClass = createEClass(INTEGRATION_VIEW_TRANSPORTER);
    createEReference(integrationViewTransporterEClass, INTEGRATION_VIEW_TRANSPORTER__CHANNEL);

    integrationTransportChannelEClass = createEClass(INTEGRATION_TRANSPORT_CHANNEL);

    // Create enums
    uoPClientServerRoleEEnum = createEEnum(UO_PCLIENT_SERVER_ROLE);
    uopFaceProfileEEnum = createEEnum(UOP_FACE_PROFILE);
    uopDesignAssuranceLevelEEnum = createEEnum(UOP_DESIGN_ASSURANCE_LEVEL);
    uopDesignAssuranceStandardEEnum = createEEnum(UOP_DESIGN_ASSURANCE_STANDARD);
    uopMessageExchangeTypeEEnum = createEEnum(UOP_MESSAGE_EXCHANGE_TYPE);
    uopPartitionTypeEEnum = createEEnum(UOP_PARTITION_TYPE);
    uopProgrammingLanguageEEnum = createEEnum(UOP_PROGRAMMING_LANGUAGE);
    uopSynchronizationStyleEEnum = createEEnum(UOP_SYNCHRONIZATION_STYLE);
    uopThreadTypeEEnum = createEEnum(UOP_THREAD_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Obtain other dependent packages
    UddlPackage theUddlPackage = (UddlPackage)EPackage.Registry.INSTANCE.getEPackage(UddlPackage.eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    architectureModelEClass.getESuperTypes().add(this.getFaceElement());
    uopUoPModelEClass.getESuperTypes().add(this.getFaceElement());
    uopElementEClass.getESuperTypes().add(this.getFaceElement());
    uopSupportingComponentEClass.getESuperTypes().add(this.getUopElement());
    uopLanguageRuntimeEClass.getESuperTypes().add(this.getUopSupportingComponent());
    uopComponentFrameworkEClass.getESuperTypes().add(this.getUopSupportingComponent());
    uopAbstractUoPEClass.getESuperTypes().add(this.getUopElement());
    uopUnitOfPortabilityEClass.getESuperTypes().add(this.getUopElement());
    uopPortableComponentEClass.getESuperTypes().add(this.getUopUnitOfPortability());
    uopPlatformSpecificComponentEClass.getESuperTypes().add(this.getUopUnitOfPortability());
    uopClientServerConnectionEClass.getESuperTypes().add(this.getUopConnection());
    uopPubSubConnectionEClass.getESuperTypes().add(this.getUopConnection());
    uopQueuingConnectionEClass.getESuperTypes().add(this.getUopPubSubConnection());
    uopSingleInstanceMessageConnectionEClass.getESuperTypes().add(this.getUopPubSubConnection());
    uopMessageTypeEClass.getESuperTypes().add(this.getUopElement());
    uopCompositeTemplateEClass.getESuperTypes().add(this.getUopMessageType());
    uopTemplateEClass.getESuperTypes().add(this.getUopMessageType());
    integrationIntegrationModelEClass.getESuperTypes().add(this.getFaceElement());
    integrationElementEClass.getESuperTypes().add(this.getFaceElement());
    integrationIntegrationContextEClass.getESuperTypes().add(this.getIntegrationElement());
    integrationUoPInstanceEClass.getESuperTypes().add(this.getIntegrationElement());
    integrationUoPInputEndPointEClass.getESuperTypes().add(this.getIntegrationTSNodePortBase());
    integrationUoPOutputEndPointEClass.getESuperTypes().add(this.getIntegrationTSNodePortBase());
    integrationTransportNodeEClass.getESuperTypes().add(this.getFaceElement());
    integrationTSNodeInputPortEClass.getESuperTypes().add(this.getIntegrationTSNodePortBase());
    integrationTSNodeOutputPortEClass.getESuperTypes().add(this.getIntegrationTSNodePortBase());
    integrationViewAggregationEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationViewFilterEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationViewSourceEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationViewSinkEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationViewTransformationEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationViewTransporterEClass.getESuperTypes().add(this.getIntegrationTransportNode());
    integrationTransportChannelEClass.getESuperTypes().add(this.getIntegrationElement());

    // Initialize classes and features; add operations and parameters
    initEClass(architectureModelEClass, ArchitectureModel.class, "ArchitectureModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getArchitectureModel_Dm(), theUddlPackage.getDataModel(), null, "dm", null, 0, -1, ArchitectureModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitectureModel_Um(), this.getUopUoPModel(), null, "um", null, 0, -1, ArchitectureModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getArchitectureModel_Im(), this.getIntegrationIntegrationModel(), null, "im", null, 0, -1, ArchitectureModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(faceElementEClass, FaceElement.class, "FaceElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFaceElement_Name(), ecorePackage.getEString(), "name", null, 0, 1, FaceElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFaceElement_Description(), ecorePackage.getEString(), "description", null, 0, 1, FaceElement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopUoPModelEClass, UopUoPModel.class, "UopUoPModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopUoPModel_Um(), this.getUopUoPModel(), null, "um", null, 0, -1, UopUoPModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUoPModel_Element(), this.getUopElement(), null, "element", null, 0, -1, UopUoPModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopElementEClass, UopElement.class, "UopElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopSupportingComponentEClass, UopSupportingComponent.class, "UopSupportingComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopSupportingComponent_Version(), ecorePackage.getEString(), "version", null, 0, 1, UopSupportingComponent.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopLanguageRuntimeEClass, UopLanguageRuntime.class, "UopLanguageRuntime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopComponentFrameworkEClass, UopComponentFramework.class, "UopComponentFramework", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopAbstractUoPEClass, UopAbstractUoP.class, "UopAbstractUoP", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopAbstractUoP_Connection(), this.getUopAbstractConnection(), null, "connection", null, 0, -1, UopAbstractUoP.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopAbstractConnectionEClass, UopAbstractConnection.class, "UopAbstractConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopAbstractConnection_Name(), ecorePackage.getEString(), "name", null, 0, 1, UopAbstractConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopAbstractConnection_Description(), ecorePackage.getEString(), "description", null, 0, 1, UopAbstractConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopAbstractConnection_ConceptualView(), theUddlPackage.getConceptualView(), null, "conceptualView", null, 0, 1, UopAbstractConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopAbstractConnection_LogicalView(), theUddlPackage.getLogicalView(), null, "logicalView", null, 0, 1, UopAbstractConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopUnitOfPortabilityEClass, UopUnitOfPortability.class, "UopUnitOfPortability", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopUnitOfPortability_Realizes(), this.getUopAbstractUoP(), null, "realizes", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopUnitOfPortability_TransportAPILanguage(), this.getUopProgrammingLanguage(), "transportAPILanguage", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopUnitOfPortability_PartitionType(), this.getUopPartitionType(), "partitionType", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopUnitOfPortability_FaceProfile(), this.getUopFaceProfile(), "faceProfile", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopUnitOfPortability_DesignAssuranceLevel(), this.getUopDesignAssuranceLevel(), "designAssuranceLevel", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopUnitOfPortability_DesignAssuranceStandard(), this.getUopDesignAssuranceStandard(), "designAssuranceStandard", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_MemoryRequirements(), this.getUopRAMMemoryRequirements(), null, "memoryRequirements", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_Thread(), this.getUopThread(), null, "thread", null, 0, -1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_SupportingComponent(), this.getUopSupportingComponent(), null, "supportingComponent", null, 0, -1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_Connection(), this.getUopConnection(), null, "connection", null, 0, -1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_LcmPort(), this.getUopLifeCycleManagementPort(), null, "lcmPort", null, 0, -1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopUnitOfPortability_ImplementedBy(), this.getIntegrationIntegrationContext(), null, "implementedBy", null, 0, 1, UopUnitOfPortability.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopPortableComponentEClass, UopPortableComponent.class, "UopPortableComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopPlatformSpecificComponentEClass, UopPlatformSpecificComponent.class, "UopPlatformSpecificComponent", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopThreadEClass, UopThread.class, "UopThread", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopThread_Period(), ecorePackage.getEFloat(), "period", null, 0, 1, UopThread.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopThread_TimeCapacity(), ecorePackage.getEFloat(), "timeCapacity", null, 0, 1, UopThread.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopThread_RelativePriority(), ecorePackage.getEInt(), "relativePriority", null, 0, 1, UopThread.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopThread_RelativeCoreAffinity(), ecorePackage.getEInt(), "relativeCoreAffinity", null, 0, 1, UopThread.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopThread_ThreadType(), this.getUopThreadType(), "threadType", null, 0, 1, UopThread.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopRAMMemoryRequirementsEClass, UopRAMMemoryRequirements.class, "UopRAMMemoryRequirements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopRAMMemoryRequirements_HeapStackMin(), ecorePackage.getEInt(), "heapStackMin", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_HeapStackTypical(), ecorePackage.getEInt(), "heapStackTypical", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_HeapStackMax(), ecorePackage.getEInt(), "heapStackMax", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_TextMax(), ecorePackage.getEInt(), "textMax", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_RoDataMax(), ecorePackage.getEInt(), "roDataMax", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_DataMax(), ecorePackage.getEInt(), "dataMax", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopRAMMemoryRequirements_BssMax(), ecorePackage.getEInt(), "bssMax", null, 0, 1, UopRAMMemoryRequirements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopConnectionEClass, UopConnection.class, "UopConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopConnection_Name(), ecorePackage.getEString(), "name", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopConnection_Description(), ecorePackage.getEString(), "description", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopConnection_Realizes(), this.getUopAbstractConnection(), null, "realizes", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopConnection_SynchronizationStyle(), this.getUopSynchronizationStyle(), "synchronizationStyle", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopConnection_Period(), ecorePackage.getEFloat(), "period", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopConnection_MapsTo(), this.getIntegrationTransportNode(), null, "mapsTo", null, 0, 1, UopConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopClientServerConnectionEClass, UopClientServerConnection.class, "UopClientServerConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopClientServerConnection_RequestType(), this.getUopMessageType(), null, "requestType", null, 0, 1, UopClientServerConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopClientServerConnection_ResponseType(), this.getUopMessageType(), null, "responseType", null, 0, 1, UopClientServerConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopClientServerConnection_Role(), this.getUoPClientServerRole(), "role", null, 0, 1, UopClientServerConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopPubSubConnectionEClass, UopPubSubConnection.class, "UopPubSubConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopPubSubConnection_MessageExchangeType(), this.getUopMessageExchangeType(), "messageExchangeType", null, 0, 1, UopPubSubConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopPubSubConnection_MessageType(), this.getUopMessageType(), null, "messageType", null, 0, 1, UopPubSubConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopQueuingConnectionEClass, UopQueuingConnection.class, "UopQueuingConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopQueuingConnection_Depth(), ecorePackage.getEInt(), "depth", null, 0, 1, UopQueuingConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopSingleInstanceMessageConnectionEClass, UopSingleInstanceMessageConnection.class, "UopSingleInstanceMessageConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopLifeCycleManagementPortEClass, UopLifeCycleManagementPort.class, "UopLifeCycleManagementPort", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopLifeCycleManagementPort_MessageExchangeType(), this.getUopMessageExchangeType(), "messageExchangeType", null, 0, 1, UopLifeCycleManagementPort.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopLifeCycleManagementPort_LcmMessageType(), this.getUopMessageType(), null, "lcmMessageType", null, 0, 1, UopLifeCycleManagementPort.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopMessageTypeEClass, UopMessageType.class, "UopMessageType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(uopCompositeTemplateEClass, UopCompositeTemplate.class, "UopCompositeTemplate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopCompositeTemplate_Realizes(), theUddlPackage.getLogicalCompositeQuery(), null, "realizes", null, 0, 1, UopCompositeTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopCompositeTemplate_IsUnion(), ecorePackage.getEBoolean(), "isUnion", null, 0, 1, UopCompositeTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopCompositeTemplate_Composition(), this.getUopTemplateComposition(), null, "composition", null, 0, -1, UopCompositeTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopTemplateCompositionEClass, UopTemplateComposition.class, "UopTemplateComposition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getUopTemplateComposition_Type(), this.getUopMessageType(), null, "type", null, 0, 1, UopTemplateComposition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getUopTemplateComposition_Rolename(), ecorePackage.getEString(), "rolename", null, 0, 1, UopTemplateComposition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopTemplateComposition_Realizes(), theUddlPackage.getLogicalQueryComposition(), null, "realizes", null, 0, 1, UopTemplateComposition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(uopTemplateEClass, UopTemplate.class, "UopTemplate", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getUopTemplate_Specification(), ecorePackage.getEString(), "specification", null, 0, 1, UopTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopTemplate_BoundQuery(), theUddlPackage.getPlatformQuery(), null, "boundQuery", null, 0, 1, UopTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getUopTemplate_EffectiveQuery(), theUddlPackage.getPlatformQuery(), null, "effectiveQuery", null, 0, 1, UopTemplate.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationIntegrationModelEClass, IntegrationIntegrationModel.class, "IntegrationIntegrationModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationIntegrationModel_Im(), this.getIntegrationIntegrationModel(), null, "im", null, 0, -1, IntegrationIntegrationModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationIntegrationModel_Element(), this.getIntegrationElement(), null, "element", null, 0, -1, IntegrationIntegrationModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationElementEClass, IntegrationElement.class, "IntegrationElement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationIntegrationContextEClass, IntegrationIntegrationContext.class, "IntegrationIntegrationContext", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationIntegrationContext_Node(), this.getIntegrationTransportNode(), null, "node", null, 0, -1, IntegrationIntegrationContext.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationIntegrationContext_Connection(), this.getIntegrationTSNodeConnection(), null, "connection", null, 0, -1, IntegrationIntegrationContext.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTSNodeConnectionEClass, IntegrationTSNodeConnection.class, "IntegrationTSNodeConnection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationTSNodeConnection_Source(), this.getIntegrationTSNodePortBase(), null, "source", null, 0, 1, IntegrationTSNodeConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationTSNodeConnection_Destination(), this.getIntegrationTSNodePortBase(), null, "destination", null, 0, 1, IntegrationTSNodeConnection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTSNodePortBaseEClass, IntegrationTSNodePortBase.class, "IntegrationTSNodePortBase", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationUoPInstanceEClass, IntegrationUoPInstance.class, "IntegrationUoPInstance", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationUoPInstance_Realizes(), this.getUopUnitOfPortability(), null, "realizes", null, 0, 1, IntegrationUoPInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getIntegrationUoPInstance_ConfigurationURI(), ecorePackage.getEString(), "configurationURI", null, 0, 1, IntegrationUoPInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationUoPInstance_Input(), this.getIntegrationUoPInputEndPoint(), null, "input", null, 0, -1, IntegrationUoPInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationUoPInstance_Output(), this.getIntegrationUoPOutputEndPoint(), null, "output", null, 0, -1, IntegrationUoPInstance.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationUoPInputEndPointEClass, IntegrationUoPInputEndPoint.class, "IntegrationUoPInputEndPoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationUoPInputEndPoint_Connection(), this.getUopConnection(), null, "connection", null, 0, 1, IntegrationUoPInputEndPoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationUoPOutputEndPointEClass, IntegrationUoPOutputEndPoint.class, "IntegrationUoPOutputEndPoint", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationUoPOutputEndPoint_Connection(), this.getUopConnection(), null, "connection", null, 0, 1, IntegrationUoPOutputEndPoint.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTransportNodeEClass, IntegrationTransportNode.class, "IntegrationTransportNode", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationTransportNode_InPort(), this.getIntegrationTSNodeInputPort(), null, "inPort", null, 0, -1, IntegrationTransportNode.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIntegrationTransportNode_OutPort(), this.getIntegrationTSNodeOutputPort(), null, "outPort", null, 0, 1, IntegrationTransportNode.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTSNodeInputPortEClass, IntegrationTSNodeInputPort.class, "IntegrationTSNodeInputPort", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationTSNodeInputPort_View(), this.getUopMessageType(), null, "view", null, 0, 1, IntegrationTSNodeInputPort.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTSNodeOutputPortEClass, IntegrationTSNodeOutputPort.class, "IntegrationTSNodeOutputPort", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationTSNodeOutputPort_View(), this.getUopMessageType(), null, "view", null, 0, 1, IntegrationTSNodeOutputPort.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationViewAggregationEClass, IntegrationViewAggregation.class, "IntegrationViewAggregation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationViewFilterEClass, IntegrationViewFilter.class, "IntegrationViewFilter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationViewSourceEClass, IntegrationViewSource.class, "IntegrationViewSource", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationViewSinkEClass, IntegrationViewSink.class, "IntegrationViewSink", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationViewTransformationEClass, IntegrationViewTransformation.class, "IntegrationViewTransformation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(integrationViewTransporterEClass, IntegrationViewTransporter.class, "IntegrationViewTransporter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntegrationViewTransporter_Channel(), this.getIntegrationTransportChannel(), null, "channel", null, 0, 1, IntegrationViewTransporter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(integrationTransportChannelEClass, IntegrationTransportChannel.class, "IntegrationTransportChannel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    // Initialize enums and add enum literals
    initEEnum(uoPClientServerRoleEEnum, UoPClientServerRole.class, "UoPClientServerRole");
    addEEnumLiteral(uoPClientServerRoleEEnum, UoPClientServerRole.CLIENT);
    addEEnumLiteral(uoPClientServerRoleEEnum, UoPClientServerRole.SERVER);

    initEEnum(uopFaceProfileEEnum, UopFaceProfile.class, "UopFaceProfile");
    addEEnumLiteral(uopFaceProfileEEnum, UopFaceProfile.GENERAL_PURPOSE);
    addEEnumLiteral(uopFaceProfileEEnum, UopFaceProfile.SECURITY);
    addEEnumLiteral(uopFaceProfileEEnum, UopFaceProfile.SAFETY_BASE);
    addEEnumLiteral(uopFaceProfileEEnum, UopFaceProfile.SAFETY_EXTENDED);

    initEEnum(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.class, "UopDesignAssuranceLevel");
    addEEnumLiteral(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.A);
    addEEnumLiteral(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.B);
    addEEnumLiteral(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.C);
    addEEnumLiteral(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.D);
    addEEnumLiteral(uopDesignAssuranceLevelEEnum, UopDesignAssuranceLevel.E);

    initEEnum(uopDesignAssuranceStandardEEnum, UopDesignAssuranceStandard.class, "UopDesignAssuranceStandard");
    addEEnumLiteral(uopDesignAssuranceStandardEEnum, UopDesignAssuranceStandard.DO_178B_ED_12B);
    addEEnumLiteral(uopDesignAssuranceStandardEEnum, UopDesignAssuranceStandard.DO_178C_ED_12C);

    initEEnum(uopMessageExchangeTypeEEnum, UopMessageExchangeType.class, "UopMessageExchangeType");
    addEEnumLiteral(uopMessageExchangeTypeEEnum, UopMessageExchangeType.INBOUND_MESSAGE);
    addEEnumLiteral(uopMessageExchangeTypeEEnum, UopMessageExchangeType.OUTBOUND_MESSAGE);

    initEEnum(uopPartitionTypeEEnum, UopPartitionType.class, "UopPartitionType");
    addEEnumLiteral(uopPartitionTypeEEnum, UopPartitionType.POSIX);
    addEEnumLiteral(uopPartitionTypeEEnum, UopPartitionType.ARINC653);

    initEEnum(uopProgrammingLanguageEEnum, UopProgrammingLanguage.class, "UopProgrammingLanguage");
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.UNSPECIFIED);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.C);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.CPP);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.JAVA);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.ADA);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.GO);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.JS);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.PYTHON);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.RUST);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.SCALA);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.SQL);
    addEEnumLiteral(uopProgrammingLanguageEEnum, UopProgrammingLanguage.TS);

    initEEnum(uopSynchronizationStyleEEnum, UopSynchronizationStyle.class, "UopSynchronizationStyle");
    addEEnumLiteral(uopSynchronizationStyleEEnum, UopSynchronizationStyle.BLOCKING);
    addEEnumLiteral(uopSynchronizationStyleEEnum, UopSynchronizationStyle.NON_BLOCKING);

    initEEnum(uopThreadTypeEEnum, UopThreadType.class, "UopThreadType");
    addEEnumLiteral(uopThreadTypeEEnum, UopThreadType.FOREGROUND);
    addEEnumLiteral(uopThreadTypeEEnum, UopThreadType.BACKGROUND);

    // Create resource
    createResource(eNS_URI);
  }

} //FacePackageImpl
