/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face.impl;

import com.epistimis.face.face.FacePackage;
import com.epistimis.face.face.IntegrationElement;
import com.epistimis.face.face.IntegrationIntegrationModel;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Integration Integration Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.impl.IntegrationIntegrationModelImpl#getIm <em>Im</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.IntegrationIntegrationModelImpl#getElement <em>Element</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IntegrationIntegrationModelImpl extends FaceElementImpl implements IntegrationIntegrationModel
{
  /**
   * The cached value of the '{@link #getIm() <em>Im</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIm()
   * @generated
   * @ordered
   */
  protected EList<IntegrationIntegrationModel> im;

  /**
   * The cached value of the '{@link #getElement() <em>Element</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getElement()
   * @generated
   * @ordered
   */
  protected EList<IntegrationElement> element;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntegrationIntegrationModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FacePackage.Literals.INTEGRATION_INTEGRATION_MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntegrationIntegrationModel> getIm()
  {
    if (im == null)
    {
      im = new EObjectContainmentEList<IntegrationIntegrationModel>(IntegrationIntegrationModel.class, this, FacePackage.INTEGRATION_INTEGRATION_MODEL__IM);
    }
    return im;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<IntegrationElement> getElement()
  {
    if (element == null)
    {
      element = new EObjectContainmentEList<IntegrationElement>(IntegrationElement.class, this, FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT);
    }
    return element;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__IM:
        return ((InternalEList<?>)getIm()).basicRemove(otherEnd, msgs);
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT:
        return ((InternalEList<?>)getElement()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__IM:
        return getIm();
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT:
        return getElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__IM:
        getIm().clear();
        getIm().addAll((Collection<? extends IntegrationIntegrationModel>)newValue);
        return;
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT:
        getElement().clear();
        getElement().addAll((Collection<? extends IntegrationElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__IM:
        getIm().clear();
        return;
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT:
        getElement().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__IM:
        return im != null && !im.isEmpty();
      case FacePackage.INTEGRATION_INTEGRATION_MODEL__ELEMENT:
        return element != null && !element.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //IntegrationIntegrationModelImpl
