/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face.impl;

import com.epistimis.face.face.FacePackage;
import com.epistimis.face.face.IntegrationTransportNode;
import com.epistimis.face.face.UopAbstractConnection;
import com.epistimis.face.face.UopConnection;
import com.epistimis.face.face.UopSynchronizationStyle;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uop Connection</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getDescription <em>Description</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getRealizes <em>Realizes</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getSynchronizationStyle <em>Synchronization Style</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getPeriod <em>Period</em>}</li>
 *   <li>{@link com.epistimis.face.face.impl.UopConnectionImpl#getMapsTo <em>Maps To</em>}</li>
 * </ul>
 *
 * @generated
 */
public class UopConnectionImpl extends MinimalEObjectImpl.Container implements UopConnection
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected static final String DESCRIPTION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDescription() <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescription()
   * @generated
   * @ordered
   */
  protected String description = DESCRIPTION_EDEFAULT;

  /**
   * The cached value of the '{@link #getRealizes() <em>Realizes</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRealizes()
   * @generated
   * @ordered
   */
  protected UopAbstractConnection realizes;

  /**
   * The default value of the '{@link #getSynchronizationStyle() <em>Synchronization Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSynchronizationStyle()
   * @generated
   * @ordered
   */
  protected static final UopSynchronizationStyle SYNCHRONIZATION_STYLE_EDEFAULT = UopSynchronizationStyle.BLOCKING;

  /**
   * The cached value of the '{@link #getSynchronizationStyle() <em>Synchronization Style</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSynchronizationStyle()
   * @generated
   * @ordered
   */
  protected UopSynchronizationStyle synchronizationStyle = SYNCHRONIZATION_STYLE_EDEFAULT;

  /**
   * The default value of the '{@link #getPeriod() <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeriod()
   * @generated
   * @ordered
   */
  protected static final float PERIOD_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getPeriod() <em>Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeriod()
   * @generated
   * @ordered
   */
  protected float period = PERIOD_EDEFAULT;

  /**
   * The cached value of the '{@link #getMapsTo() <em>Maps To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMapsTo()
   * @generated
   * @ordered
   */
  protected IntegrationTransportNode mapsTo;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UopConnectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FacePackage.Literals.UOP_CONNECTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getDescription()
  {
    return description;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDescription(String newDescription)
  {
    String oldDescription = description;
    description = newDescription;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__DESCRIPTION, oldDescription, description));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UopAbstractConnection getRealizes()
  {
    if (realizes != null && realizes.eIsProxy())
    {
      InternalEObject oldRealizes = (InternalEObject)realizes;
      realizes = (UopAbstractConnection)eResolveProxy(oldRealizes);
      if (realizes != oldRealizes)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FacePackage.UOP_CONNECTION__REALIZES, oldRealizes, realizes));
      }
    }
    return realizes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UopAbstractConnection basicGetRealizes()
  {
    return realizes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRealizes(UopAbstractConnection newRealizes)
  {
    UopAbstractConnection oldRealizes = realizes;
    realizes = newRealizes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__REALIZES, oldRealizes, realizes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UopSynchronizationStyle getSynchronizationStyle()
  {
    return synchronizationStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSynchronizationStyle(UopSynchronizationStyle newSynchronizationStyle)
  {
    UopSynchronizationStyle oldSynchronizationStyle = synchronizationStyle;
    synchronizationStyle = newSynchronizationStyle == null ? SYNCHRONIZATION_STYLE_EDEFAULT : newSynchronizationStyle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__SYNCHRONIZATION_STYLE, oldSynchronizationStyle, synchronizationStyle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getPeriod()
  {
    return period;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPeriod(float newPeriod)
  {
    float oldPeriod = period;
    period = newPeriod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__PERIOD, oldPeriod, period));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntegrationTransportNode getMapsTo()
  {
    if (mapsTo != null && mapsTo.eIsProxy())
    {
      InternalEObject oldMapsTo = (InternalEObject)mapsTo;
      mapsTo = (IntegrationTransportNode)eResolveProxy(oldMapsTo);
      if (mapsTo != oldMapsTo)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, FacePackage.UOP_CONNECTION__MAPS_TO, oldMapsTo, mapsTo));
      }
    }
    return mapsTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IntegrationTransportNode basicGetMapsTo()
  {
    return mapsTo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMapsTo(IntegrationTransportNode newMapsTo)
  {
    IntegrationTransportNode oldMapsTo = mapsTo;
    mapsTo = newMapsTo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, FacePackage.UOP_CONNECTION__MAPS_TO, oldMapsTo, mapsTo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case FacePackage.UOP_CONNECTION__NAME:
        return getName();
      case FacePackage.UOP_CONNECTION__DESCRIPTION:
        return getDescription();
      case FacePackage.UOP_CONNECTION__REALIZES:
        if (resolve) return getRealizes();
        return basicGetRealizes();
      case FacePackage.UOP_CONNECTION__SYNCHRONIZATION_STYLE:
        return getSynchronizationStyle();
      case FacePackage.UOP_CONNECTION__PERIOD:
        return getPeriod();
      case FacePackage.UOP_CONNECTION__MAPS_TO:
        if (resolve) return getMapsTo();
        return basicGetMapsTo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case FacePackage.UOP_CONNECTION__NAME:
        setName((String)newValue);
        return;
      case FacePackage.UOP_CONNECTION__DESCRIPTION:
        setDescription((String)newValue);
        return;
      case FacePackage.UOP_CONNECTION__REALIZES:
        setRealizes((UopAbstractConnection)newValue);
        return;
      case FacePackage.UOP_CONNECTION__SYNCHRONIZATION_STYLE:
        setSynchronizationStyle((UopSynchronizationStyle)newValue);
        return;
      case FacePackage.UOP_CONNECTION__PERIOD:
        setPeriod((Float)newValue);
        return;
      case FacePackage.UOP_CONNECTION__MAPS_TO:
        setMapsTo((IntegrationTransportNode)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case FacePackage.UOP_CONNECTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case FacePackage.UOP_CONNECTION__DESCRIPTION:
        setDescription(DESCRIPTION_EDEFAULT);
        return;
      case FacePackage.UOP_CONNECTION__REALIZES:
        setRealizes((UopAbstractConnection)null);
        return;
      case FacePackage.UOP_CONNECTION__SYNCHRONIZATION_STYLE:
        setSynchronizationStyle(SYNCHRONIZATION_STYLE_EDEFAULT);
        return;
      case FacePackage.UOP_CONNECTION__PERIOD:
        setPeriod(PERIOD_EDEFAULT);
        return;
      case FacePackage.UOP_CONNECTION__MAPS_TO:
        setMapsTo((IntegrationTransportNode)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case FacePackage.UOP_CONNECTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case FacePackage.UOP_CONNECTION__DESCRIPTION:
        return DESCRIPTION_EDEFAULT == null ? description != null : !DESCRIPTION_EDEFAULT.equals(description);
      case FacePackage.UOP_CONNECTION__REALIZES:
        return realizes != null;
      case FacePackage.UOP_CONNECTION__SYNCHRONIZATION_STYLE:
        return synchronizationStyle != SYNCHRONIZATION_STYLE_EDEFAULT;
      case FacePackage.UOP_CONNECTION__PERIOD:
        return period != PERIOD_EDEFAULT;
      case FacePackage.UOP_CONNECTION__MAPS_TO:
        return mapsTo != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", description: ");
    result.append(description);
    result.append(", synchronizationStyle: ");
    result.append(synchronizationStyle);
    result.append(", period: ");
    result.append(period);
    result.append(')');
    return result.toString();
  }

} //UopConnectionImpl
