/**
 * generated by Xtext 2.30.0
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.face.impl;

import com.epistimis.face.face.FacePackage;
import com.epistimis.face.face.UopSingleInstanceMessageConnection;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Uop Single Instance Message Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UopSingleInstanceMessageConnectionImpl extends UopPubSubConnectionImpl implements UopSingleInstanceMessageConnection
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UopSingleInstanceMessageConnectionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FacePackage.Literals.UOP_SINGLE_INSTANCE_MESSAGE_CONNECTION;
  }

} //UopSingleInstanceMessageConnectionImpl
