/*
 * generated by Xtext 2.30.0
 */
/*
 * Copyright (c) 2022, 2023 Epistimis LLC (http://www.epistimis.com).
 */
package com.epistimis.face.scoping;

import com.epistimis.uddl.scoping.UddlScopeProvider;

public abstract class AbstractFaceScopeProvider extends UddlScopeProvider {
}
